# Generated by Selenium IDE

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options


class TestPsd:
    def setup_method(self):
        chrome_options = Options()
        chrome_options.add_experimental_option("debuggerAddress", "127.0.0.1:9000")
        chrome_driver = r'C:\Users\paul.wu\PycharmProjects\drivers\chromedriver.exe'
        self.driver = webdriver.Chrome(executable_path=chrome_driver, options=chrome_options)
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def test_psdautologin(self, logid):
        self.driver.get("http://psdtool.tc.net/psdTool/")
        self.driver.set_window_size(1173, 826)
        time.sleep(2)
        element = self.driver.find_element(By.LINK_TEXT, "Transaction Management")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "Raw Edi").click()
        time.sleep(2)
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.ID, "ctl00_BodyContent_ctl00_txtLogId").click()
        self.driver.find_element(By.ID, "ctl00_BodyContent_ctl00_txtLogId").send_keys(logid)
        self.driver.find_element(By.ID, "ctl00_BodyContent_ctl00_btnGetData").click()
        time.sleep(2)
        # 4 | click | id=ctl00_BodyContent_ctl00_rbTNYes |
        self.driver.find_element(By.ID, "ctl00_BodyContent_ctl00_rbTNYes").click()
        # 5 | click | id=ctl00_BodyContent_ctl00_chkWaiveCharges |
        self.driver.find_element(By.ID, "ctl00_BodyContent_ctl00_chkWaiveCharges").click()
        # 6 | click | id=ctl00_BodyContent_ctl00_btnSubmit |
        # self.driver.find_element(By.ID, "ctl00_BodyContent_ctl00_btnSubmit").click()

